"""Swagger Petstore API client.

Auto-generated by Ipê v0.1.0.
"""

from swagger_petstore.client import SwaggerPetstoreClient
from swagger_petstore.models.error import Error
from swagger_petstore.models.pet import Pet

__all__ = [
    "Error",
    "Pet",
    "SwaggerPetstoreClient",
]
