from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from ipe.models.blueprint import APIBlueprint, OutputFile


class NamingConvention(Protocol):
    def class_name(self, raw: str) -> str: ...
    def method_name(self, raw: str) -> str: ...
    def field_name(self, raw: str) -> str: ...
    def module_name(self, raw: str) -> str: ...


class LanguageTarget(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def naming(self) -> NamingConvention: ...

    def transform(self, blueprint: APIBlueprint) -> dict[str, Any]: ...

    def plan(self, data: dict[str, Any]) -> list[OutputFile]: ...

    def get_template_dir(self) -> Path: ...

    def validate_config(self, config: dict[str, Any]) -> bool: ...

    def get_default_config(self) -> dict[str, Any]: ...
