from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from ipe.models.standard import StandardOperation


class NamingConvention(Protocol):
    def class_name(self, raw: str) -> str: ...
    def method_name(self, raw: str) -> str: ...
    def field_name(self, raw: str) -> str: ...
    def module_name(self, raw: str) -> str: ...


class LanguageTarget(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def naming(self) -> NamingConvention: ...

    def resolve_type(self, schema_type: str, schema_format: str | None) -> str: ...

    def group(
        self, operations: list[StandardOperation]
    ) -> dict[str, list[StandardOperation]]: ...

    @property
    def template_dir(self) -> Path: ...

    def get_default_config(self) -> dict[str, Any]: ...

    def filters(self) -> dict[str, Callable[..., Any]]: ...
